[[redirects]]
  from = "/workshop"
  to = "https://forms.formium.io/f/6004c711d0a32c0001f496ff"
  status = 302
  force = true

[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UC8O1RTDK93NT-f2eTjY3p5A"
  status = 302
  force = true

[[redirects]]
  from = "/bookclub"
  to = "https://www.meetup.com/es-ES/rubyperu/events/288030547/"
  status = 302
  force = true
